project:
  type: website
  preview: 
    port: 3000

  render: 
    - "*.qmd"
    - "!es/"
    -  "README.md"

website:
  title: "Javier Ribal del Río"
  favicon: "img/Javier-Ribal-del-Rio.jpg"
  navbar:

    left: 
      - proyects.qmd
      - blog.qmd
    right:
     
      - href: es/index.html
        text: "<span class='language-icon icon-es'></span>Spanish"
      - icon: github
        href: https://github.com/JavierRibaldelRio
        target: blank
      - icon: linkedin
        href: https://linkedin.com/in/javier-ribal-del-rio
        target: blank
      - icon: envelope
        href: mailto:javierribaldelrio@gmail.com

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles/styles.css
    includes:
      in-header: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">





