project:
  type: website
  output-dir: ../_site/es

  preview: 
    port: 3000

website:
  title: "Javier Ribal del Río"
  navbar:
    left:
      - pages/proyects.qmd
      - blog.qmd

    right:       
      - href: ../index.html
        text: "<span class='language-icon icon-en'></span>English"    
      - icon: github
        href: https://github.com/JavierRibaldelRio
        target: blank
      - icon: linkedin
        target: blank
        href: https://linkedin.com/in/javier-ribal-del-rio
      - icon: envelope
        href: mailto:javierribaldelrio@gmail.com

format:
  html:
    theme: sandstone
    css: ../styles/styles.css



